[project]
name = "cooking-app"
version = "0.1.0"
description = "This is a web app created using Python for my journey to learn AI engineering. This has always been an app I wanted for myself with my own customisations"
readme = "README.md"
authors = [
    { name = "PhhDD", email = "sdchenhewen@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
    "uuid6>=2025.0.1",
]

[project.scripts]
cooking-app = "cooking_app:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
