"""add recipe name

Revision ID: 1af018130f63
Revises: 94b62635b503
Create Date: 2026-10-04 20:07:43.171504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af018130f63'
down_revision: Union[str, Sequence[str], None] = '94b62635b503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('recipe_name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'recipe_name')
    # ### end Alembic commands ###
