"""create ingredient table

Revision ID: 70a1ad0a9638
Revises: 7939aac4ce2b
Create Date: 2026-10-06 23:58:17.186615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a1ad0a9638'
down_revision: Union[str, Sequence[str], None] = '7939aac4ce2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('vegetable', 'fruit', 'meat', 'fish', 'seafood', 'dairy', 'grain', 'legume', 'nut', 'herb_spice', 'oil_fat', 'sauce_condiment', 'other', name='ingredientcategory'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_ingredient_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    # ### end Alembic commands ###
