"""add recipe step dependency table

Revision ID: 7939aac4ce2b
Revises: a67d5e4c4338
Create Date: 2026-10-04 23:56:42.671355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7939aac4ce2b'
down_revision: Union[str, Sequence[str], None] = 'a67d5e4c4338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_recipe_step_recipe_id_id', 'recipe_steps', ['recipe_id', 'id'])
    op.create_table('recipe_step_dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('predecessor_step_id', sa.UUID(), nullable=False),
    sa.Column('successor_step_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('predecessor_step_id <> successor_step_id', name='ck_recipe_step_no_self_dependency'),
    sa.ForeignKeyConstraint(['recipe_id', 'predecessor_step_id'], ['recipe_steps.recipe_id', 'recipe_steps.id'], name='fk_dependency_predecessor'),
    sa.ForeignKeyConstraint(['recipe_id', 'successor_step_id'], ['recipe_steps.recipe_id', 'recipe_steps.id'], name='fk_dependency_successor'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_dependency_recipe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'predecessor_step_id', 'successor_step_id', name='uq_recipe_step_dependency')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_step_dependencies')    
    op.drop_constraint('uq_recipe_step_recipe_id_id', 'recipe_steps', type_='unique')
    # ### end Alembic commands ###
