"""add source language enum

Revision ID: 94b62635b503
Revises: 4e81f88a5730
Create Date: 2026-10-04 19:18:35.950033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94b62635b503'
down_revision: Union[str, Sequence[str], None] = '4e81f88a5730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    source_lang_enum = sa.Enum('en', 'zh', name='sourcelang')
    source_lang_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'source_lang',
                    existing_type=sa.VARCHAR(length=30),
                    type_=source_lang_enum,
                    existing_nullable=False,
                    postgresql_using='source_lang::sourcelang',
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    source_lang_enum = sa.Enum('en', 'zh', name='sourcelang')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recipes', 'source_lang',
               existing_type=source_lang_enum,
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###

    source_lang_enum.drop(op.get_bind(), checkfirst=True)
