"""add protein to ingredient category

Revision ID: 9b8feca2730d
Revises: 7ee3431aba22
Create Date: 2026-10-07 22:16:50.925288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b8feca2730d'
down_revision: Union[str, Sequence[str], None] = '7ee3431aba22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TYPE ingredientcategory "
        "ADD VALUE IF NOT EXISTS 'protein'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
